# Aiven database connection details
spring.datasource.url=${jdbc:mysql://avnadmin:AVNS_lHuY39nleddpNPKSJjd@mysql-c3e200c-monilpatelb31-3672.i.aivencloud.com:16083/defaultdb?ssl-mode=REQUIRED}
spring.datasource.username=${avnadmin}
spring.datasource.password=${AVNS_lHuY39nleddpNPKSJjd}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true